import { RecommendedVideoDto } from "./recommended-video.dto";

export class VideoDto {
  type: string;
  title: string;
  videoId: string;
  videoThumbnails: object;
  storyboards: object;
  description: string;
  descriptionHtml: string;
  published: number;
  publishedText: string;
  keywords: Array<string>;
  viewCount: number;
  likeCount: number;
  dislikeCount: number;
  paid: boolean;
  premium: boolean;
  isFamilyFriendly: boolean;
  allowedRegions: Array<string>;
  genre: string;
  genreUrl: string;
  author: string;
  authorId: string;
  authorUrl: string;
  authorThumbnails: Array<object>;
  authorVerified: boolean;
  subCount: number;
  lengthSeconds: number;
  allowRatings: boolean;
  rating: string;
  isListed: boolean;
  liveNow: boolean;
  isUpcoming: boolean;
  dashUrl: string;
  adaptiveFormats: Array<object>;
  formatStreams: Array<object>;
  captions: object;
  recommendedVideos: Array<RecommendedVideoDto>;
}
